### ISSUE TITLE
osmium-tool dependency missing for `asf-tools` PyPI distribution

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/asf-tools#227]
[osmium-tool](https://github.com/osmcode/osmium-tool) is a C++ command line tool for working with OpenStreetMap data that's used in `asf_tools.watermasking.generate_osm_tiles` which new as of asf-tools v0.7.0. 

Since it's C++ based and doesn't have Python binding, it's not distributed on PyPI (only conda-forge), and anyone installing `asf_tools` from PyPI and attempting to run `generate_osm_tiles` will encounter an error like:
```
```

So that the developers understand there's a conda-forge-only dependency, we should: include a comment in the `pyproject.toml` like:
```toml
dependencies = [
    ...
    "numpy",
    # "osmium-tool",  # C++ CLI tool only available via conda-forge and used by `asf_tools.watermasking.generate_osm_tiles`
    "pyogrio",
    ...
]
```

and include a function in `gerenate_osm_tiles` that checks that `osmium` is installed and throws an error telling users how to install it.
```[tasklist]
### Tasks
- [x] Comment in `pyproject.toml`
- [x] Error thrown if `osium-tool` is not installed when runng `gerneate_osm_tiles` that includes install instructions
- [x] `asf-tools` package README and API docs should note the optional dependency and provide install instuctions
- [x] add `__init__.py` to `asf_tools.watermasking`
- [x] Nit: Rename `asf-tools/src/asf_tools/REAME.MD` -> `asf-tools/src/asf_tools/REAME.md`
```
